version: '3'
services:
  server:
    build: ./python
    volumes:
      - ${WEB_ROOT}:/code
    command: python ${RUN_COMMAND}
    ports:
      - "${PUBLIC_PORT}:5000"
    depends_on:
      - db
  db:
    image: postgres
