version: '3'
services:
  server:
    image: node:6.9
    volumes:
      - ${WEB_ROOT}:/code
    ports:
      - "${PUBLIC_PORT}:3001"
    environment:
      - DEP_DB_HOST=${db}
      - PUB_API_PORT=${PUBLIC_PORT}
    working_dir: /code
    command: npm start
    depends_on:
      - db
  db:
    image: mongo:2
    command: mongod --dbpath /data/db --noauth
    volumes:
      - ${DATA_ROOT}:/data/db
